name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.ACCESS_TOKEN_GITHUB }}
          password: ${{ secrets.ACCESS_TOKEN_GITHUB }}

      - name: Build Docker image
        run: docker build -t your-docker-username/your-image-name .

      - name: Push Docker image
        run: docker push your-docker-username/your-image-name
